version: "3"

services:
    mongodb:
        image: mongo
        container_name: guy_mongo
        environment: 
            - MONGO_INITDB_DATABASE=test_db
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
        volumes: 
            - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
            - ./mongo-volume:/data/db
        ports:
            - "27017:27017"
        healthcheck:
            test:  ["CMD", "docker-healthcheck"]
            interval: 10s
            timeout: 5s
            retries: 10
    rabbitmq:
        image: rabbitmq
        container_name: guy_rabbitmq
        volumes:
            - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
            - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
            - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
        environment:
            RABBITMQ_ERLANG_COOKIE: s3cr3tc00ki3
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: admin
        ports:
            - 5672:5672
            - 15672:15672
        healthcheck:
            test: ["CMD", "curl", "-f", "http://admin:admin@localhost:15672"]
            interval: 10s
            timeout: 10s
            retries: 5
    #web:
    #    image: guy/node-web-app
    #    container_name: guy_web_app
    #    ports:
    #       - 8080:8080
    #    links:
    #        - mongodb
    #    depends_on:
    #       rabbitmq:
    #           condition: service_healthy
          
